# Generated by Django 5.2.5 on 2025-08-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_worked_on', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('case_type', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('tax', 'Tax'), ('family', 'Family'), ('other', 'Other')], max_length=50)),
                ('date_of_case', models.DateField()),
                ('status', models.CharField(default='Open', max_length=50)),
                ('stage', models.CharField(choices=[('initial', 'Initial Intake'), ('discovery', 'Discovery'), ('analysis', 'Analysis'), ('trial', 'Trial Preparation'), ('closed', 'Closed')], default='initial', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('boss_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Portal_main_app.case')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Portal_main_app.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='defendant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defendant_cases', to='Portal_main_app.company'),
        ),
        migrations.AddField(
            model_name='case',
            name='plaintiff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintiff_cases', to='Portal_main_app.company'),
        ),
        migrations.CreateModel(
            name='CompanyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Portal_main_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='LawFirmNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('law_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Portal_main_app.lawfirm')),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('law_firm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyers', to='Portal_main_app.lawfirm')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='defense_lawyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defense_cases', to='Portal_main_app.lawyer'),
        ),
        migrations.AddField(
            model_name='case',
            name='plaintiff_lawyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintiff_cases', to='Portal_main_app.lawyer'),
        ),
        migrations.CreateModel(
            name='LawyerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Portal_main_app.lawyer')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting_docs', 'Waiting for Documents'), ('waiting_next', 'Waiting for Next Steps'), ('complete', 'Complete')], default='not_started', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Portal_main_app.case')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bank_stmt', 'Bank Statement'), ('check', 'Check'), ('invoice', 'Invoice'), ('excel', 'Excel Table'), ('other', 'Other')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, help_text='e.g., Client, Subpoena, Discovery', max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='Portal_main_app.case')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='Portal_main_app.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Portal_main_app.task')),
            ],
        ),
    ]
