# Generated by Django 5.2.5 on 2025-08-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='defendant',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='plaintiff',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
