# Generated by Django 5.2.5 on 2025-08-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_main_app', '0002_alter_case_defendant_alter_case_plaintiff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawfirm',
            name='boss_name',
        ),
        migrations.AddField(
            model_name='case',
            name='hired_by',
            field=models.CharField(choices=[('plantiff', 'Plaintiff'), ('defendant', 'Defendant'), ('other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('civil', 'Civil'), ('litigation', 'Litigation'), ('tax', 'Tax'), ('Accounting', 'Accounting'), ('Chapter7', 'chapter7'), ('Chapter11', 'chapter11'), ('Chapter13', 'chapter13'), ('other', 'Other'), ('Monitorship', 'Monitorship'), ('Receivership', 'Receivership')], max_length=50),
        ),
    ]
