# Generated by Django 5.2.5 on 2025-08-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_main_app', '0003_remove_lawfirm_boss_name_case_hired_by_lawyer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='summary',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
